### ISSUE TITLE
Problem when building

### ISSUE THREAD

**Issue by firefixmaarten** [foomo/simplecert#10]
Seems to be a non existing library in go mod ? 
```
go get -u -v github.com/foomo/simplecert
go: github.com/foomo/simplecert upgrade => v1.7.1
go get: github.com/foomo/simplecert@v1.7.1 requires
        github.com/exoscale/egoscale@v1.19.0: reading github.com/exoscale/egoscale/go.mod at revision v1.19.0: unknown revision v1.19.0
```

Also could you stick to semver for versioning in the future ? => v1.7 should be v1.7.0

**Comment by dreadl0ck** [comment]
Thanks for the pull request fixing the modules, will merge it in a second.

> Also could you stick to semver for versioning in the future ? => v1.7 should be v1.7.0

Will do!
