### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by malvinpratama** [foomo/simplecert#13]
i try to install and i got some error

github.com/go-acme/lego/v3/providers/dns/linodev4
../../../go/pkg/mod/github.com/go-acme/lego/v3@v3.9.0/providers/dns/linodev4/linodev4.go:104:58: undefined: linodego.Version

because of that my project show the error like this 

github.com/go-acme/lego/v3@v3.9.0/providers/dns/linodev4/linodev4.go
line 104
undefined: linodego.Version

i think that problem related with this pr
https://github.com/linode/linodego/pull/156

**Comment by dreadl0ck** [comment]
Hi there,

thanks for reporting!

Could you please provide the version of go you are using ($ go version) as well as the Operating System you are working on?

Depending on your Go version, make sure Go modules are enabled for your project,
otherwise building simplecert won't work.

You can check if modules have been manually activated with:

    $ echo $GO111MODULE

Starting in Go 1.13, module mode will be the default for all development, so it's no longer necessary to set the env var.

**Comment by malvinpratama** [comment]
go version 
go1.15 darwin/amd64

catalina 10.15.7

i use go mod before i add simplecert and that work fine
but after i add simplecert i got error 
github.com/go-acme/lego/v3@v3.9.0/providers/dns/linodev4/linodev4.go
line 104
undefined: linodego.Version

i try to go get again and after I observed it turned out some error like this
github.com/go-acme/lego/v3/providers/dns/linodev4
../../../go/pkg/mod/github.com/go-acme/lego/v3@v3.9.0/providers/dns/linodev4/linodev4.go:104:58: undefined: linodego.Version

first go get i not see the error because i forget about -u -v

**Comment by dreadl0ck** [comment]
Alright, next you could try to flush your go module cache, maybe something is corrupted there:

    $ go clean -modcache

Afterwards try to run go mod tidy from your project root, it will download and check the dependencies of your project:

    $ go mod tidy

If it fails, please share the output for further troubleshooting.

**Comment by malvinpratama** [comment]
go mod tidy work fine

after that go build / go run get some error

'#' github.com/go-acme/lego/v3/providers/dns/linodev4
../../../go/pkg/mod/github.com/go-acme/lego/v3@v3.9.0/providers/dns/linodev4/linodev4.go:104:58: undefined: linodego.Version

**Comment by dreadl0ck** [comment]
Hm, that's weird. I'm also unable to reproduce this.

Can you share the output of the go mod tidy after cleaning the module cache?
I need to see which versions of the dependencies are fetched.

Please also share the go.mod file if possible.
Maybe the your project has an indirect dependency that is causing this issue.

**Comment by dreadl0ck** [comment]
I've updated the lego package to v4, this should resolve your error.

If it did not, please ping me to reopen this issue.
