### ISSUE TITLE
Don't use log.Fatal in simplecert.go

### ISSUE THREAD

**Issue by zjuanma** [foomo/simplecert#14]
I have errors when try to create certificates and I can't recuperate from it because of use of log.Fatal.
I think is better return a error and lets client library to manage it.

**Comment by dreadl0ck** [comment]
What errors are you getting exactly?

For things like invalid config settings I prefer to fail early and explicitly.

**Comment by zjuanma** [comment]
I'm getting this error:

2020/11/19 00:38:19 [FATAL] simplecert: failed to obtain cert: error: one or more domains had a problem:
[xxxx] [xxxx] acme: error presenting token: request to change TXT record for DuckDNS returned the following result (KO) this does not match expectation (OK) used url [https://www.duckdns.org/update?clear=false&domains=xxxx&token=yyy]

I know is a fatal error, but I have a web interface for administration listening in another port and I could show a descriptive error to the administrator of the service. But using log.Fatal my server exit and I lose the web interface for administration.

That's why I think is better return a error.

**Comment by dreadl0ck** [comment]
Fair enough - I've pushed a new release that will return all errors that occur in simplecert.Init instead.

https://github.com/foomo/simplecert/releases/tag/v1.7.7

Let me know if that works for you

**Comment by zjuanma** [comment]
Thanks.
Now, it works perfect .
