### ISSUE TITLE
Possible to provide custom certs with simplecert

### ISSUE THREAD

**Issue by aqsyounas** [foomo/simplecert#17]
Hi, 

I wanted to check if we can use existing certs(godaddy/self signed ones) with simplecert instead of letting simplecert to get those from letsencrypt?

Thanks for awesome tool. 

Best Regards.

**Comment by dreadl0ck** [comment]
Hi there,

never tried that, but should be possible in general.
On startup, simplecert checks if the cacheDir exists and contains certs, and if so, loads them.

For example, lets say your cacheDir is /etc/letsencrypt/testapp, the following files will be created by simplecert during normal operation:

```
tree /etc/letsencrypt/testapp
/etc/letsencrypt/testapp
├── cert.pem
├── CertResource.json
├── key.pem
├── simplecert.log
└── SSLUser.json
```

Create the folder manually and add your cert.pem and key.pem in there and they should be used by simplecert.
If that fails for some reason, provide the error message here and I'll take a look.
