### ISSUE TITLE
simplecert.Init erroring wrongly

### ISSUE THREAD

**Issue by azukaar** [foomo/simplecert#23]
The simplecert.Init is throwing an error when it cannot renew certificate, but it should just return a nil, and invoke the FailedToRenewCertificate callback so that certificate renewal issues can be sovled the same way whether the server is already started or not

(@dreadl0ck sorry for the ping, but you mentioned we should ping you!)

**Comment by dreadl0ck** [comment]
Hey thanks for raising this, I will look into it asap.

**Comment by dreadl0ck** [comment]
Fixed in: https://github.com/foomo/simplecert/releases/tag/v1.8.5

Thanks for reporting!

**Comment by azukaar** [comment]
Thanks you!
