### ISSUE TITLE
simplecert.Init should maybe init with previous certificate when renew fails on init

### ISSUE THREAD

**Issue by azukaar** [foomo/simplecert#24]
This is an extension to #14 that was fixed earlier:
Here's a scenario:
 - I have a working certificate with 3 domains including the main domain for the administration
 - I add an additional domain from the administration, and restart the server
 - SimpleCert will try to replace the certificate with the 4th domain
 - The 4th domain is invalid, so It will fail to init, the admin panel won't be accessible anymore to fix the 4th domain

How I could see this could works, is for example having a setting "fallbackToPreviousCert" that would do exactly what it suggest when failing to review on init? What do you think?

**Comment by dreadl0ck** [comment]
Thanks for reporting, will look into this soon.

**Comment by dreadl0ck** [comment]
Fixed in https://github.com/foomo/simplecert/releases/tag/v1.8.6

Let me know if there are any issues.

**Comment by azukaar** [comment]
Amazing will test, thanks!
