### ISSUE TITLE
go get fails on dependency retrieval

### ISSUE THREAD

**Issue by henhouse** [foomo/simplecert#6]
Hi there, thanks for the library. Looking forward to trying it.

When attempting to vendor the package, it fails with this error:
```
go: finding github.com/foomo/tlsconfig latest
go get: github.com/akamai/AkamaiOPEN-edgegrid-golang@v0.9.0 updating to
	github.com/akamai/AkamaiOPEN-edgegrid-golang@v0.9.3 requires
	github.com/h2non/gock@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by dreadl0ck** [comment]
Hi, thanks for reporting!

What version of go and and what version of simplecert are you using?

**Comment by henhouse** [comment]
I was using the latest Go 1.13.5 and was trying to vendor the latest version of simplecert via `go get -u -v github.com/foomo/simplecert`. Tried this on both Mac and PC.

To reproduce you'll likely need to delete the cache folder for go modules. I'm assuming something has happened with a dependency of a dependency.

**Comment by dreadl0ck** [comment]
I'm not able to reproduce this, when cleaning the modcache and fetching the package everything works fine.

    $ go clean --modcache
    $ go get -u -v github.com/foomo/simplecert
    ...
    $ go version
    go version go1.13.4 darwin/amd64

Could you try to delete the modcache on your system and fetch the package again?

**Comment by dreadl0ck** [comment]
Interestingly it fails on a linux machine with a different error for me:

    $ go version
    go version go1.13.5 linux/amd64
    $ go clean --modcache
    $ go get github.com/foomo/simplecert
    package github.com/sacloud/libsacloud/api: cannot find package "github.com/sacloud/libsacloud/api" in any of:
	/snap/go/4901/src/github.com/sacloud/libsacloud/api (from $GOROOT)
	/home/user/go/src/github.com/sacloud/libsacloud/api (from $GOPATH)

**Comment by dreadl0ck** [comment]
Was able to fetch and build the package by doing:

        $ export GO111MODULE=on
	$ go get github.com/foomo/simplecert
	go: finding github.com/foomo/simplecert v1.6.4
	go: downloading github.com/foomo/simplecert v1.6.4
	go: extracting github.com/foomo/simplecert v1.6.4
	go: downloading github.com/lextoumbourou/goodhosts v2.1.0+incompatible
	go: downloading github.com/go-acme/lego/v3 v3.1.0
	go: downloading github.com/foomo/tlsconfig v0.0.0-20180418120404-b67861b076c9
	go: extracting github.com/lextoumbourou/goodhosts v2.1.0+incompatible
	go: extracting github.com/foomo/tlsconfig v0.0.0-20180418120404-b67861b076c9
	go: extracting github.com/go-acme/lego/v3 v3.1.0
	go: downloading golang.org/x/crypto v0.0.0-20190923035154-9ee001bba392
	go: downloading github.com/cenkalti/backoff/v3 v3.0.0
	go: downloading golang.org/x/net v0.0.0-20190930134127-c5a3c61f89f3
	go: downloading gopkg.in/square/go-jose.v2 v2.3.1
	go: downloading github.com/labbsr0x/bindman-dns-webhook v1.0.2
	go: downloading github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190923070751-d615ccdd3e09
	go: downloading github.com/dnsimple/dnsimple-go v0.30.0
	go: downloading github.com/namedotcom/go v0.0.0-20180403034216-08470befbe04
	go: downloading github.com/liquidweb/liquidweb-go v1.6.0
	go: extracting github.com/cenkalti/backoff/v3 v3.0.0
	go: extracting github.com/dnsimple/dnsimple-go v0.30.0
	go: extracting github.com/labbsr0x/bindman-dns-webhook v1.0.2
	go: extracting gopkg.in/square/go-jose.v2 v2.3.1
	go: extracting github.com/liquidweb/liquidweb-go v1.6.0
	go: extracting github.com/namedotcom/go v0.0.0-20180403034216-08470befbe04
	go: downloading github.com/gophercloud/gophercloud v0.4.0
	go: downloading github.com/ovh/go-ovh v0.0.0-20181109152953-ba5adb4cf014
	go: downloading github.com/labbsr0x/goh v1.0.1
	go: downloading golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
	go: extracting github.com/ovh/go-ovh v0.0.0-20181109152953-ba5adb4cf014
	go: downloading gopkg.in/ini.v1 v1.48.0
	go: extracting golang.org/x/crypto v0.0.0-20190923035154-9ee001bba392
	go: extracting golang.org/x/net v0.0.0-20190930134127-c5a3c61f89f3
	go: extracting golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
	go: extracting github.com/labbsr0x/goh v1.0.1
	go: downloading github.com/cpu/goacmedns v0.0.1
	go: extracting gopkg.in/ini.v1 v1.48.0
	go: downloading github.com/akamai/AkamaiOPEN-edgegrid-golang v0.9.0
	go: downloading google.golang.org/api v0.10.0
	go: extracting github.com/cpu/goacmedns v0.0.1
	go: extracting github.com/akamai/AkamaiOPEN-edgegrid-golang v0.9.0
	go: downloading github.com/nrdcg/namesilo v0.2.1
	go: downloading github.com/pkg/errors v0.8.1
	go: downloading cloud.google.com/go v0.46.3
	go: extracting github.com/nrdcg/namesilo v0.2.1
	go: downloading github.com/sacloud/libsacloud v1.27.1
	go: extracting github.com/gophercloud/gophercloud v0.4.0
	go: extracting github.com/pkg/errors v0.8.1
	go: downloading github.com/Azure/go-autorest/autorest v0.9.1
	go: extracting github.com/sacloud/libsacloud v1.27.1
	go: extracting cloud.google.com/go v0.46.3
	go: extracting github.com/Azure/go-autorest/autorest v0.9.1
	go: downloading github.com/Azure/go-autorest/autorest/to v0.3.0
	go: downloading github.com/aws/aws-sdk-go v1.24.4
	go: extracting github.com/Azure/go-autorest/autorest/to v0.3.0
	go: downloading github.com/sirupsen/logrus v1.4.2
	go: downloading github.com/go-errors/errors v1.0.1
	go: downloading golang.org/x/text v0.3.2
	go: extracting github.com/sirupsen/logrus v1.4.2
	go: downloading github.com/Azure/go-autorest/autorest/azure/auth v0.3.0
	go: extracting github.com/go-errors/errors v1.0.1
	go: downloading github.com/Azure/azure-sdk-for-go v33.4.0+incompatible
	go: extracting github.com/Azure/go-autorest/autorest/azure/auth v0.3.0
	go: downloading github.com/dimchansky/utfbom v1.1.0
	go: extracting github.com/dimchansky/utfbom v1.1.0
	go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.2
	go: extracting github.com/konsorten/go-windows-terminal-sequences v1.0.2
	go: downloading github.com/vultr/govultr v0.1.4
	go: extracting github.com/vultr/govultr v0.1.4
	go: downloading github.com/Azure/go-autorest/autorest/adal v0.6.0
	go: extracting github.com/Azure/go-autorest/autorest/adal v0.6.0
	go: downloading github.com/OpenDNS/vegadns2client v0.0.0-20180418235048-a3fa4a771d87
	go: extracting github.com/OpenDNS/vegadns2client v0.0.0-20180418235048-a3fa4a771d87
	go: downloading github.com/nrdcg/auroradns v1.0.0
	go: extracting github.com/nrdcg/auroradns v1.0.0
	go: extracting golang.org/x/text v0.3.2
	go: downloading golang.org/x/sys v0.0.0-20190924062700-2aa67d56cdd7
	go: extracting github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190923070751-d615ccdd3e09
	go: extracting google.golang.org/api v0.10.0
	go: extracting golang.org/x/sys v0.0.0-20190924062700-2aa67d56cdd7
	go: downloading github.com/iij/doapi v0.0.0-20190504054126-0bbf12d6d7df
	go: extracting github.com/iij/doapi v0.0.0-20190504054126-0bbf12d6d7df
	go: extracting github.com/aws/aws-sdk-go v1.24.4
	go: downloading github.com/transip/gotransip v5.8.2+incompatible
	go: downloading google.golang.org/grpc v1.23.1
	go: extracting github.com/transip/gotransip v5.8.2+incompatible
	go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
	go: extracting github.com/dgrijalva/jwt-go v3.2.0+incompatible
	go: downloading github.com/miekg/dns v1.1.17
	go: extracting google.golang.org/grpc v1.23.1
	go: extracting github.com/miekg/dns v1.1.17
	go: downloading google.golang.org/genproto v0.0.0-20190916214212-f660b8655731
	go: downloading google.golang.org/appengine v1.6.3
	go: downloading gopkg.in/ns1/ns1-go.v2 v2.0.0-20190923172200-72e0216bb8b5
	go: extracting gopkg.in/ns1/ns1-go.v2 v2.0.0-20190923172200-72e0216bb8b5
	go: downloading github.com/google/go-querystring v1.0.0
	go: downloading github.com/Azure/go-autorest/autorest/date v0.2.0
	go: extracting google.golang.org/appengine v1.6.3
	go: extracting github.com/Azure/go-autorest/autorest/date v0.2.0
	go: downloading github.com/exoscale/egoscale v0.18.1
	go: extracting github.com/google/go-querystring v1.0.0
	go: downloading github.com/Azure/go-autorest/logger v0.1.0
	go: downloading github.com/linode/linodego v0.10.0
	go: downloading github.com/Azure/go-autorest/tracing v0.5.0
	go: downloading github.com/cloudflare/cloudflare-go v0.10.2
	go: downloading github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
	go: downloading github.com/json-iterator/go v1.1.7
	go: downloading github.com/decker502/dnspod-go v0.2.0
	go: extracting github.com/exoscale/egoscale v0.18.1
	go: extracting github.com/decker502/dnspod-go v0.2.0
	go: extracting github.com/Azure/go-autorest/logger v0.1.0
	go: extracting github.com/Azure/go-autorest/tracing v0.5.0
	go: downloading github.com/golang/protobuf v1.3.2
	go: downloading go.uber.org/ratelimit v0.1.0
	go: downloading github.com/Azure/go-autorest/autorest/azure/cli v0.3.0
	go: extracting github.com/json-iterator/go v1.1.7
	go: extracting github.com/cloudflare/cloudflare-go v0.10.2
	go: extracting github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
	go: extracting github.com/linode/linodego v0.10.0
	go: extracting google.golang.org/genproto v0.0.0-20190916214212-f660b8655731
	go: extracting go.uber.org/ratelimit v0.1.0
	go: extracting github.com/Azure/go-autorest/autorest/azure/cli v0.3.0
	go: extracting github.com/golang/protobuf v1.3.2
	go: downloading github.com/nrdcg/goinwx v0.6.1
	go: downloading go.opencensus.io v0.22.1
	go: downloading github.com/gofrs/uuid v3.2.0+incompatible
	go: downloading github.com/oracle/oci-go-sdk v10.0.0+incompatible
	go: downloading github.com/modern-go/reflect2 v1.0.1
	go: downloading gopkg.in/resty.v1 v1.12.0
	go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
	go: extracting github.com/nrdcg/goinwx v0.6.1
	go: downloading github.com/kolo/xmlrpc v0.0.0-20190909154602-56d5ec7c422e
	go: extracting github.com/gofrs/uuid v3.2.0+incompatible
	go: extracting go.opencensus.io v0.22.1
	go: extracting github.com/modern-go/reflect2 v1.0.1
	go: extracting github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
	go: downloading golang.org/x/time v0.0.0-20190921001708-c4c64cad1fd0
	go: downloading github.com/timewasted/linode v0.0.0-20160829202747-37e84520dcf7
	go: downloading github.com/googleapis/gax-go/v2 v2.0.5
	go: downloading github.com/mitchellh/mapstructure v1.1.2
	go: extracting github.com/kolo/xmlrpc v0.0.0-20190909154602-56d5ec7c422e
	go: downloading github.com/go-ini/ini v1.48.0
	go: extracting gopkg.in/resty.v1 v1.12.0
	go: downloading github.com/fatih/structs v1.1.0
	go: extracting github.com/timewasted/linode v0.0.0-20160829202747-37e84520dcf7
	go: extracting golang.org/x/time v0.0.0-20190921001708-c4c64cad1fd0
	go: downloading github.com/mitchellh/go-homedir v1.1.0
	go: downloading github.com/google/uuid v1.1.1
	go: extracting github.com/googleapis/gax-go/v2 v2.0.5
	go: extracting github.com/go-ini/ini v1.48.0
	go: extracting github.com/mitchellh/mapstructure v1.1.2
	go: downloading github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
	go: extracting github.com/fatih/structs v1.1.0
	go: extracting github.com/mitchellh/go-homedir v1.1.0
	go: extracting github.com/google/uuid v1.1.1
	go: extracting github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
	go: extracting github.com/oracle/oci-go-sdk v10.0.0+incompatible
	go: extracting github.com/Azure/azure-sdk-for-go v33.4.0+incompatible
	go: downloading github.com/Azure/go-autorest/autorest/validation v0.2.0
	go: extracting github.com/Azure/go-autorest/autorest/validation v0.2.0
	go: finding github.com/foomo/tlsconfig v0.0.0-20180418120404-b67861b076c9
	go: finding github.com/go-acme/lego/v3 v3.1.0
	go: finding github.com/lextoumbourou/goodhosts v2.1.0+incompatible
	go: finding github.com/cpu/goacmedns v0.0.1
	go: finding github.com/aliyun/alibaba-cloud-sdk-go v0.0.0-20190923070751-d615ccdd3e09
	go: finding github.com/nrdcg/auroradns v1.0.0
	go: finding github.com/Azure/azure-sdk-for-go v33.4.0+incompatible
	go: finding golang.org/x/crypto v0.0.0-20190923035154-9ee001bba392
	go: finding github.com/cenkalti/backoff/v3 v3.0.0
	go: finding golang.org/x/net v0.0.0-20190930134127-c5a3c61f89f3
	go: finding github.com/Azure/go-autorest/autorest/adal v0.6.0
	go: finding github.com/Azure/go-autorest/autorest v0.9.1
	go: finding github.com/cloudflare/cloudflare-go v0.10.2
	go: finding github.com/labbsr0x/bindman-dns-webhook v1.0.2
	go: finding github.com/Azure/go-autorest/autorest/azure/auth v0.3.0
	go: finding github.com/Azure/go-autorest/autorest/to v0.3.0
	go: finding golang.org/x/text v0.3.2
	go: finding github.com/miekg/dns v1.1.17
	go: finding github.com/gophercloud/gophercloud v0.4.0
	go: finding gopkg.in/square/go-jose.v2 v2.3.1
	go: finding github.com/Azure/go-autorest/autorest/validation v0.2.0
	go: finding github.com/pkg/errors v0.8.1
	go: finding github.com/decker502/dnspod-go v0.2.0
	go: finding github.com/Azure/go-autorest/tracing v0.5.0
	go: finding github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
	go: finding github.com/dnsimple/dnsimple-go v0.30.0
	go: finding golang.org/x/time v0.0.0-20190921001708-c4c64cad1fd0
	go: finding golang.org/x/sys v0.0.0-20190924062700-2aa67d56cdd7
	go: finding golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
	go: finding github.com/labbsr0x/goh v1.0.1
	go: finding github.com/Azure/go-autorest/logger v0.1.0
	go: finding gopkg.in/ini.v1 v1.48.0
	go: finding github.com/Azure/go-autorest/autorest/date v0.2.0
	go: finding github.com/json-iterator/go v1.1.7
	go: finding github.com/sirupsen/logrus v1.4.2
	go: finding github.com/google/go-querystring v1.0.0
	go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
	go: finding github.com/akamai/AkamaiOPEN-edgegrid-golang v0.9.0
	go: finding github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
	go: finding github.com/go-errors/errors v1.0.1
	go: finding github.com/Azure/go-autorest/autorest/azure/cli v0.3.0
	go: finding github.com/dimchansky/utfbom v1.1.0
	go: finding github.com/exoscale/egoscale v0.18.1
	go: finding github.com/modern-go/reflect2 v1.0.1
	go: finding github.com/iij/doapi v0.0.0-20190504054126-0bbf12d6d7df
	go: finding google.golang.org/api v0.10.0
	go: finding github.com/aws/aws-sdk-go v1.24.4
	go: finding github.com/nrdcg/goinwx v0.6.1
	go: finding github.com/mitchellh/go-homedir v1.1.0
	go: finding github.com/timewasted/linode v0.0.0-20160829202747-37e84520dcf7
	go: finding cloud.google.com/go v0.46.3
	go: finding github.com/google/uuid v1.1.1
	go: finding github.com/liquidweb/liquidweb-go v1.6.0
	go: finding github.com/fatih/structs v1.1.0
	go: finding github.com/go-ini/ini v1.48.0
	go: finding github.com/kolo/xmlrpc v0.0.0-20190909154602-56d5ec7c422e
	go: finding github.com/gofrs/uuid v3.2.0+incompatible
	go: finding github.com/linode/linodego v0.10.0
	go: finding github.com/mitchellh/mapstructure v1.1.2
	go: finding github.com/nrdcg/namesilo v0.2.1
	go: finding github.com/namedotcom/go v0.0.0-20180403034216-08470befbe04
	go: finding google.golang.org/grpc v1.23.1
	go: finding gopkg.in/ns1/ns1-go.v2 v2.0.0-20190923172200-72e0216bb8b5
	go: finding github.com/googleapis/gax-go/v2 v2.0.5
	go: finding github.com/ovh/go-ovh v0.0.0-20181109152953-ba5adb4cf014
	go: finding github.com/oracle/oci-go-sdk v10.0.0+incompatible
	go: finding go.opencensus.io v0.22.1
	go: finding gopkg.in/resty.v1 v1.12.0
	go: finding github.com/OpenDNS/vegadns2client v0.0.0-20180418235048-a3fa4a771d87
	go: finding github.com/sacloud/libsacloud v1.27.1
	go: finding github.com/golang/protobuf v1.3.2
	go: finding github.com/transip/gotransip v5.8.2+incompatible
	go: finding github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
	go: finding go.uber.org/ratelimit v0.1.0
	go: finding github.com/vultr/govultr v0.1.4
	go: finding google.golang.org/genproto v0.0.0-20190916214212-f660b8655731

I've pushed a new release of simplecert v1.6.4 with an updated go.sum file (by running go mod tidy), check if that works for you.

**Comment by henhouse** [comment]
It worked now!

Not sure if it was the tidy release, or the modcache clear. I guess somewhere there was a messed up version on a dependency. Nice! Thanks for the help 😄
